version: '3.3'
services:
  jenkins:
    build:
      context: .
    image: jenkins
    ports:
     - "8080:8080"
     - "50000:50000"
    environment:
     - CASC_JENKINS_CONFIG=/var/jenkins_casc
    volumes:
     - ./config:/var/jenkins_casc
